### ISSUE TITLE
Grapi error when guest joins a group

### ISSUE THREAD

**Issue by aksdb** [Kopano-dev/kopano-docker#13] opened 2020-03-29 11:58 UTC
In the currently provided `examples/meet` setup, whenever I join a public session as guest, it just hangs with an endless "loading" indicator. I see the user in the session, but no picture and audio.

In the logs I see:
```
kopano_grapi        | 2020-03-29 13:56:03,098 rest7     [   65] ERROR    unhandled exception while processing request
kopano_grapi        | Traceback (most recent call last):
kopano_grapi        |   File "/usr/lib/kopano/python3-extras/lib/python3.7/site-packages/falcon/api.py", line 244, in __call__
kopano_grapi        |     responder(req, resp, **params)
kopano_grapi        |   File "/usr/lib/python3/dist-packages/grapi/api/v1/decorators.py", line 21, in wrapperResourceException
kopano_grapi        |     return f(resource, req, resp, **params)
kopano_grapi        |   File "/usr/lib/python3/dist-packages/grapi/api/v1/decorators.py", line 40, in wrapperRequireResourceHandler
kopano_grapi        |     return f(resource, req, resp, **params)
kopano_grapi        |   File "/usr/lib/python3/dist-packages/grapi/api/v1/api.py", line 31, in on_get
kopano_grapi        |     return self.getResource(req).on_get(req, resp, *args, **kwargs)
kopano_grapi        |   File "/usr/lib/python3/dist-packages/grapi/backend/ldap/user.py", line 196, in on_get
kopano_grapi        |     data = value[0]
kopano_grapi        | IndexError: list index out of range
```

**Comment by aksdb** [comment] 2020-03-29 13:17
Hmm nope, the error wasn't the blocking issue. A connection limit on the TURN server was.

But still: this error only shows up when joining guest sessions, so I guess there is still some bug - just not as critical as it seemed :)

**Comment by fbartels** [comment] 2020-03-29 18:53
Hi @aksdb,

can you share a bit more about your environment? I am unable to reproduce the above error in grapi when logging in with a guest account.

**Comment by aksdb** [comment] 2020-03-30 07:26
Sure thing:

```
$ git describe --always
0e06017
```

```
$ docker-compose images
       Container                 Repository           Tag       Image Id       Size  
-------------------------------------------------------------------------------------
kopano_grapi               kopano/kopano_core        latest   698d3b8633da   594.7 MB
kopano_kapi                kopano/kopano_core        latest   698d3b8633da   594.7 MB
kopano_kopano_konnect_1    kopano/kopano_konnect     latest   bf1332d56dec   85.45 MB
kopano_kopano_kustomer_1   kopano/kustomerd          latest   5c23d1ca0656   10.4 MB 
kopano_kopano_kwmserver_   kopano/kopano_kwmserver   latest   9a0671a91c58   27.98 MB
1                                                                                    
kopano_kopano_meet_1       kopano/kopano_meet        latest   e50a5718397e   430.6 MB
kopano_kopano_ssl_1        kopano/kopano_ssl         latest   6b1414d40ab8   12.06 MB
kopano_ldap                kopano/kopano_ldap_demo   latest   a16d084d45ee   275.7 MB
kopano_web_1               kopano/kopano_web         latest   609a2c211586   33.2 MB 
```

```
$ cat .env
# please consult https://github.com/kopano-dev/kopano-docker
# for possible configuration values and their impact

# Access to the Kopano Turn service can be requested at https://portal.kopano.com/content/turn-server-access-request
TURN_USER=
TURN_PASSWORD=

# Defines how Kopano can be accessed from the outside world
FQDN=my.domain
FQDNCLEANED=my.domain
DEFAULTREDIRECT=/meet
EMAIL=self_signed
CADDY=2015
HTTP=80
HTTPS=443

TZ=Europe/Berlin

LDAP_CONTAINER=kopano_ldap_demo
LDAP_ORGANISATION="Kopano Demo"
LDAP_DOMAIN=my.domain
LDAP_BASE_DN=dc=my,dc=domain
LDAP_SERVER=ldap://ldap:389
LDAP_ADMIN_PASSWORD=F9614754F9A0BF397F1AB784401BF2F5
LDAP_READONLY_USER_PASSWORD=77865102B7105B661C0322D54381380A
LDAP_BIND_DN=cn=readonly,dc=my,dc=domain
LDAP_BIND_PW=77865102B7105B661C0322D54381380A
LDAP_SEARCH_BASE=dc=my,dc=domain

# Settings for test environments
INSECURE=yes

# Docker and docker-compose settings
# Docker Repository to push to/pull from
docker_repo=kopano
COMPOSE_PROJECT_NAME=kopano
```

So it should be as close to a default setup as possible.

I then open a new group chat with "user1/user1", copy the group link, go to another private browser session and use that there. As soon as that guest session joins, the mentioned error shows up in the `grapi` log.

**Comment by fbartels** [comment] 2020-03-30 12:02
Ok, I was now able to reproduce the message. I have created https://jira.kopano.io/browse/KC-1734 for followup.

Thanks for reporting!

As this does not block usage or is an error with the containers in general I will now close this issue.

**Closed as completed by fbartels** 2020-03-30 12:02 UTC
Labels: bug
